#!/bin/bash
# 05_run_mafft.sh
# Aligns single-copy orthologs using MAFFT L-INS-i algorithm
# Uses GNU parallel to process multiple loci simultaneously
# Optimized for local machine with 20 cores
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 5: Multiple Sequence Alignment"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Check if unaligned sequences exist
if [ ! -d "single_copy_orthologs/unaligned_aa" ]; then
    echo "ERROR: single_copy_orthologs/unaligned_aa directory not found!"
    echo "Please run 04_extract_orthologs.sh first."
    exit 1
fi

# Move to unaligned directory
cd single_copy_orthologs/unaligned_aa

# Create output directory
mkdir -p ../aligned_aa

# Create locus list
ls *.fas > locus_names.txt
num_loci=$(wc -l < locus_names.txt)

echo "Number of loci to align: ${num_loci}"
echo "Using MAFFT L-INS-i algorithm (accurate alignment for conserved regions)"
echo "Processing up to 20 loci in parallel..."
echo ""

# Run MAFFT in parallel (20 jobs = 20 cores)
cat locus_names.txt | parallel -j 20 --progress '
    locus={}
    locus_base=$(basename ${locus} .fas)

    mafft --localpair --maxiterate 1000 ${locus} > ../aligned_aa/${locus_base}_aligned.fas 2>/dev/null
'

cd ../..

echo ""
echo "=========================================="
echo "STEP 5 Complete!"
echo "=========================================="
echo ""
echo "Aligned sequences are in: single_copy_orthologs/aligned_aa/"
echo "Number of aligned loci: $(ls single_copy_orthologs/aligned_aa/*.fas 2>/dev/null | wc -l)"
echo ""
echo "Next step: Run 06_run_aliscore_alicut.sh to trim alignments"
echo ""
