#!/bin/bash
# 07_concatenate.sh
# Concatenates trimmed alignments into supermatrix using FASconCAT-G
# Converts partition definitions to IQ-TREE format
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 7: Concatenation & Partition Definition"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Check if trimmed alignments exist
if [ ! -d "single_copy_orthologs/trimmed_aa" ]; then
    echo "ERROR: single_copy_orthologs/trimmed_aa directory not found!"
    echo "Please run 06_run_aliscore_alicut.sh first."
    exit 1
fi

# Check if FASconCAT-G exists
if [ ! -f "scripts/FASconCAT-G.pl" ]; then
    echo "ERROR: FASconCAT-G.pl not found!"
    echo "Please run setup_phylo_env.sh first."
    exit 1
fi

# Move to trimmed alignments directory
cd single_copy_orthologs/trimmed_aa

echo "Running FASconCAT-G to concatenate trimmed alignments..."
echo ""

# Run FASconCAT-G in automated mode
perl ../../scripts/FASconCAT-G.pl -s -i

echo ""
echo "Concatenation complete!"
echo ""

# Convert partition file to IQ-TREE format
if [ -f "FcC_info.xls" ]; then
    echo "Converting partition definitions to IQ-TREE format..."
    python ../../scripts/convert_fasconcat_to_partition.py FcC_info.xls partition_def.txt
    echo "Partition file created: partition_def.txt"
    echo ""
fi

# Display information about the supermatrix
if [ -f "FcC_smatrix.fas" ]; then
    echo "=========================================="
    echo "Supermatrix Statistics"
    echo "=========================================="
    echo ""
    num_taxa=$(grep -c "^>" FcC_smatrix.fas)
    total_length=$(head -2 FcC_smatrix.fas | tail -1 | wc -c)

    echo "Number of taxa: ${num_taxa}"
    echo "Total alignment length: ~${total_length} amino acids"
    echo ""

    if [ -f "partition_def.txt" ]; then
        num_partitions=$(wc -l < partition_def.txt)
        echo "Number of partitions: ${num_partitions}"
        echo ""
        echo "First few partitions:"
        head -5 partition_def.txt
        echo "..."
        echo ""
    fi
fi

cd ../..

echo "=========================================="
echo "STEP 7 Complete!"
echo "=========================================="
echo ""
echo "Output files in single_copy_orthologs/trimmed_aa/:"
echo "  - FcC_smatrix.fas     : Concatenated supermatrix"
echo "  - partition_def.txt   : IQ-TREE partition definitions"
echo "  - FcC_info.xls        : Detailed concatenation info"
echo ""
echo "Next steps:"
echo "  Run 08a_iqtree_partition_search.sh   : Find best partitioning scheme"
echo "  Run 08b_iqtree_concat_tree.sh        : Infer concatenated ML tree"
echo "  Run 08c_iqtree_gene_trees.sh         : Infer individual gene trees"
echo "  Run 08d_astral_species_tree.sh       : Infer coalescent species tree"
echo ""
