#!/bin/bash
# 08b_iqtree_concat_tree.sh
# Infers concatenated maximum likelihood phylogeny using IQ-TREE
# Uses best partitioning scheme from partition search
# Includes 1000 ultrafast bootstrap replicates with BNNI
# Optimized for local machine with 20 cores
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 8b: Concatenated ML Tree Inference"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Settings
THREADS=20
SUPERMATRIX="single_copy_orthologs/trimmed_aa/FcC_supermatrix.fas"
PARTITIONS="partition_search.best_scheme.nex"
OUTPUT_PREFIX="concatenated_ML_tree"

# Check if files exist
if [ ! -f "${SUPERMATRIX}" ]; then
    echo "ERROR: Supermatrix not found at ${SUPERMATRIX}"
    echo "Please run 07_concatenate.sh first."
    exit 1
fi

if [ ! -f "${PARTITIONS}" ]; then
    echo "ERROR: Partition scheme not found at ${PARTITIONS}"
    echo "Please run 08a_iqtree_partition_search.sh first."
    exit 1
fi

echo "Supermatrix: ${SUPERMATRIX}"
echo "Partition scheme: ${PARTITIONS}"
echo "Threads: ${THREADS}"
echo ""
echo "This step will:"
echo "  1. Infer the maximum likelihood tree"
echo "  3. Calculate 1000 ultrafast bootstrap replicates"
echo "  4. Apply BNNI to reduce potential bootstrap overestimation"
echo ""
echo "This may take several hours to days depending on dataset size..."
echo ""

# Run IQ-TREE ML inference
iqtree \
    -s ${SUPERMATRIX} \
    -spp ${PARTITIONS} \
    -nt ${THREADS} \
    -safe \
    -pre ${OUTPUT_PREFIX} \
    -bb 1000 \
    -bnni

echo ""
echo "=========================================="
echo "STEP 8b Complete!"
echo "=========================================="
echo ""
echo "Output files:"
echo "  - concatenated_ML_tree.treefile     : Final ML tree (use this for visualization)"
echo "  - concatenated_ML_tree.log          : Detailed log with model info"
echo "  - concatenated_ML_tree.iqtree       : Full analysis report"
echo ""
echo "Your concatenated phylogeny is ready for visualization!"
echo ""
echo "Optional next steps:"
echo "  - Run 08c_iqtree_gene_trees.sh to infer individual gene trees"
echo "  - Run 08d_astral_species_tree.sh to infer coalescent species tree"
echo ""
