#!/bin/bash
# 08c_iqtree_gene_trees.sh
# Infers individual gene trees for all loci using IQ-TREE
# Uses GNU parallel to process multiple genes simultaneously
# Optimized for local machine with 20 cores
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 8c: Individual Gene Tree Inference"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Check if trimmed alignments exist
if [ ! -d "single_copy_orthologs/trimmed_aa" ]; then
    echo "ERROR: single_copy_orthologs/trimmed_aa directory not found!"
    echo "Please run 06_run_aliscore_alicut.sh first."
    exit 1
fi

# Move to trimmed alignments directory
cd single_copy_orthologs/trimmed_aa

# Create directory for gene trees
mkdir -p gene_trees

# Create list of alignment files
ls *.fas | grep -v "FcC_smatrix" > alignments_list.txt 2>/dev/null || true
num_loci=$(wc -l < alignments_list.txt)

echo "Number of loci: ${num_loci}"
echo "Processing up to 20 genes in parallel..."
echo ""

# Run IQ-TREE for each gene in parallel
cat alignments_list.txt | parallel -j 20 --progress '
    locus={}
    locus_base=$(basename ${locus} .fas | sed "s/_trimmed$//" | sed "s/_aligned$//")

    iqtree \
        -s ${locus} \
        -m MFP \
        -bb 1000 \
        -pre gene_trees/${locus_base} \
        -nt 1 \
        -safe \
	-bnni \
	-czb \
        > gene_trees/${locus_base}.log 2>&1
'

# Collect all gene trees into a single file
echo ""
echo "Collecting gene trees..."
cat gene_trees/*.treefile > all_gene_trees.tre 2>/dev/null || true

cd ../..

echo ""
echo "=========================================="
echo "STEP 8c Complete!"
echo "=========================================="
echo ""
echo "Output files:"
echo "  - single_copy_orthologs/trimmed_aa/gene_trees/*.treefile  : Individual gene trees"
echo "  - single_copy_orthologs/trimmed_aa/all_gene_trees.tre     : All trees concatenated"
echo ""
echo "Number of gene trees: $(grep -c "^" single_copy_orthologs/trimmed_aa/all_gene_trees.tre 2>/dev/null || echo 0)"
echo ""
echo "Next step: Run 08d_astral_species_tree.sh to infer coalescent species tree"
echo ""
