#!/bin/bash
# 02_run_compleasm.sh
# Runs compleasm to identify single-copy orthologs from genome assemblies
# Uses liliopsida_odb10 lineage (monocots) for palm phylogenomics
# Optimized for local machine with 20 cores
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 2: Single-Copy Ortholog Identification"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Settings
LINEAGE="liliopsida_odb10"
THREADS=10  # Use 8 threads per genome to allow parallel processing
LOG_DIR="logs"

# Create logs directory
mkdir -p ${LOG_DIR}

echo "BUSCO Lineage: ${LINEAGE}"
echo "Threads per genome: ${THREADS}"
echo ""

# Check if genome_list.txt exists
if [ ! -f genome_list.txt ]; then
    echo "ERROR: genome_list.txt not found!"
    echo "Please run 01_download_genomes.sh first."
    exit 1
fi

# Count genomes
num_genomes=$(wc -l < genome_list.txt)
echo "Number of genomes to process: ${num_genomes}"
echo ""

# Process genomes with GNU parallel for efficiency
# Run up to 2 genomes simultaneously (2 × 8 cores = 16 cores)
echo "Starting compleasm analysis..."
echo "Processing up to 2 genome in parallel..."
echo ""

cat genome_list.txt | parallel -j 2 --progress '
    genome={}
    genome_name=$(basename ${genome} | sed "s/\.fasta$//" | sed "s/\.fna$//")

    echo "Processing ${genome_name}..."

    compleasm run \
        -a ${genome} \
        -o ${genome_name}_compleasm \
        -l '"${LINEAGE}"' \
        -t '"${THREADS}"' \
        > '"${LOG_DIR}"'/${genome_name}.compleasm.log 2>&1

    echo "Completed ${genome_name}"
'

echo ""
echo "=========================================="
echo "STEP 2 Complete!"
echo "=========================================="
echo ""
echo "Compleasm results are in *_compleasm/ directories"
echo ""
echo "Next steps:"
echo "  1. Run 03_generate_qc_report.sh to assess genome quality"
echo "  2. Review QC report and exclude low-quality genomes if needed"
echo "  3. Run 04_extract_orthologs.sh to extract single-copy orthologs"
echo ""
