#!/bin/bash
# 03_generate_qc_report.sh
# Generates quality control report from compleasm results
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 3: Generate Quality Control Report"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Generate QC report
echo "Generating QC report from compleasm results..."
bash scripts/generate_qc_report.sh qc_report.csv

echo ""
echo "QC Report generated: qc_report.csv"
echo ""
cat qc_report.csv
echo ""
echo "=========================================="
echo "Quality Assessment Guidelines"
echo "=========================================="
echo ""
echo "  Excellent  (>95% complete): Retain"
echo "  Good       (90-95%): Retain"
echo "  Acceptable (85-90%): Case-by-case"
echo "  Questionable (70-85%): Consider excluding"
echo "  Poor       (<70%): Recommend excluding"
echo ""
echo "=========================================="
echo "STEP 3 Complete!"
echo "=========================================="
echo ""
echo "Review the QC report above."
echo ""
echo "If you need to exclude low-quality genomes:"
echo "  1. Edit genome_list.txt to remove unwanted genomes"
echo "  2. Or create genome_list_filtered.txt with only high-quality genomes"
echo ""
echo "Next step: Run 04_extract_orthologs.sh"
echo ""
