#!/bin/bash
# 04_extract_orthologs.sh
# Extracts single-copy orthologs from compleasm results
# Reorganizes sequences into per-locus FASTA files
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 4: Extract Single-Copy Orthologs"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Extract orthologs using the helper script
echo "Extracting orthologs from compleasm results..."
echo "This will create single_copy_orthologs/unaligned_aa/ directory"
echo ""

bash scripts/extract_orthologs.sh liliopsida

echo ""
echo "=========================================="
echo "STEP 4 Complete!"
echo "=========================================="
echo ""

# Count extracted loci
num_loci=$(ls single_copy_orthologs/unaligned_aa/*.fas 2>/dev/null | wc -l)
echo "Extracted ${num_loci} single-copy orthologous loci"
echo ""
echo "Output directory: single_copy_orthologs/unaligned_aa/"
echo ""
echo "Next step: Run 05_run_mafft.sh to align sequences"
echo ""
