#!/bin/bash
# 08a_iqtree_partition_search.sh
# Searches for best partitioning scheme using IQ-TREE ModelFinder
# Uses TESTMERGEONLY to merge partitions with same model
# Optimized for local machine with 20 cores
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 8a: Partition Model Selection"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Settings
THREADS=20
SUPERMATRIX="single_copy_orthologs/trimmed_aa/FcC_supermatrix.fas"
PARTITIONS="single_copy_orthologs/trimmed_aa/partition_def.txt"
OUTPUT_PREFIX="partition_search"

# Check if files exist
if [ ! -f "${SUPERMATRIX}" ]; then
    echo "ERROR: Supermatrix not found at ${SUPERMATRIX}"
    echo "Please run 07_concatenate.sh first."
    exit 1
fi

if [ ! -f "${PARTITIONS}" ]; then
    echo "ERROR: Partition file not found at ${PARTITIONS}"
    echo "Please run 07_concatenate.sh first."
    exit 1
fi

echo "Supermatrix: ${SUPERMATRIX}"
echo "Partitions: ${PARTITIONS}"
echo "Threads: ${THREADS}"
echo ""
echo "This step finds the best partitioning scheme by:"
echo "  1. Testing models for each partition"
echo "  2. Merging partitions with the same best model"
echo "  3. Reducing model complexity while preserving fit"
echo ""
echo "This may take several hours depending on dataset size..."
echo ""

# Run IQ-TREE partition search
iqtree \
    -s ${SUPERMATRIX} \
    -spp ${PARTITIONS} \
    -nt ${THREADS} \
    -pre ${OUTPUT_PREFIX} \
    -m TESTMERGEONLY \
    -mset Q.plant \
    -mrate E,I,G,I+G,I+R 

echo ""
echo "=========================================="
echo "STEP 8a Complete!"
echo "=========================================="
echo ""
echo "Output files:"
echo "  - partition_search.best_scheme.nex  : Best partitioning scheme (use in next step)"
echo "  - partition_search.log              : Detailed log"
echo ""
echo "Next step: Run 08b_iqtree_concat_tree.sh to infer the ML tree"
echo ""
