#!/bin/bash
# 08d_astral_species_tree.sh
# Infers species tree using ASTRAL-III coalescent method
# Accounts for incomplete lineage sorting using multispecies coalescent
# Generated by Claude phylo_from_buscos skill

set -e

echo "=========================================="
echo "STEP 8d: ASTRAL Coalescent Species Tree"
echo "=========================================="
echo ""

# Activate conda environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate phylo

# Settings
GENE_TREES="single_copy_orthologs/trimmed_aa/all_gene_trees.tre"
OUTPUT_TREE="astral_species_tree.tre"

# Check if gene trees exist
if [ ! -f "${GENE_TREES}" ]; then
    echo "ERROR: Gene trees file not found at ${GENE_TREES}"
    echo "Please run 08c_iqtree_gene_trees.sh first."
    exit 1
fi

# Check if ASTRAL exists
if ! command -v astral &> /dev/null; then
    echo "ERROR: ASTRAL not found in PATH"
    echo "Please ensure the phylo conda environment is activated."
    exit 1
fi

# Count gene trees
num_trees=$(grep -c "^" ${GENE_TREES})
echo "Number of gene trees: ${num_trees}"
echo ""
echo "Running ASTRAL to infer coalescent species tree..."
echo "ASTRAL finds the tree that agrees with the most gene tree quartets"
echo ""

# Run ASTRAL
astral \
    -i ${GENE_TREES} \
    -o ${OUTPUT_TREE} \
    2>&1 | tee astral.log

echo ""
echo "=========================================="
echo "STEP 8d Complete!"
echo "=========================================="
echo ""
echo "Output files:"
echo "  - ${OUTPUT_TREE}   : ASTRAL species tree (coalescent method)"
echo "  - astral.log       : ASTRAL analysis log"
echo ""
echo "Branch support values are local posterior probabilities"
echo ""
echo "=========================================="
echo "All Phylogenetic Analyses Complete!"
echo "=========================================="
echo ""
echo "Final tree files:"
echo "  1. concatenated_ML_tree.treefile  : ML tree from concatenated supermatrix"
echo "  2. ${OUTPUT_TREE}                 : Species tree from coalescent method"
echo ""
echo "Compare both trees to assess concordance and impact of incomplete lineage sorting"
echo ""
