#!/bin/bash
# setup_phylo_env.sh
# Sets up unified conda environment for phylogenomics workflow
# Generated by Claude phylo_from_buscos skill for palm phylogeny project

set -e

echo "=========================================="
echo "Phylogenomics Environment Setup"
echo "=========================================="
echo ""

# Check if conda is available
if ! command -v conda &> /dev/null; then
    echo "ERROR: conda not found. Please install Miniconda or Anaconda first."
    echo "Visit: https://docs.conda.io/en/latest/miniconda.html"
    exit 1
fi

# Environment name
ENV_NAME="phylo"

echo "Creating conda environment: ${ENV_NAME}"
echo ""

# Create environment with all tools
mamba create -n ${ENV_NAME} -y \
    -c conda-forge -c bioconda \
    python=3.9 \
    astral-tree \
    compleasm \
    mafft \
    trimal \
    clipkit \
    bmge \
    iqtree \
    perl \
    perl-bioperl \
    parallel \
    wget \
    ncbi-datasets-cli \
    openjdk

echo ""
echo "Environment created successfully!"
echo ""

# Setup Aliscore and ALICUT Perl scripts
echo "Setting up Aliscore and ALICUT Perl scripts..."
echo ""

# Activate environment
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate ${ENV_NAME}

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create scripts directory if it doesn't exist
mkdir -p "${SCRIPT_DIR}/scripts"

# Ask user preference for script source
echo "Aliscore/ALICUT Script Source Options:"
echo "  1) Use predownloaded scripts (from Paul Frandsen's tutorial, tested)"
echo "  2) Download latest versions from official repository"
echo ""
read -p "Enter choice [1-2] (default: 1): " SCRIPT_CHOICE
SCRIPT_CHOICE=${SCRIPT_CHOICE:-1}

if [ "${SCRIPT_CHOICE}" = "1" ]; then
    echo "Using predownloaded Aliscore/ALICUT scripts..."

    # Check if running from within the Claude skills directory

        if wget -q https://github.com/brunoasm/my_claude_skills/tree/main/phylo_from_buscos/scripts/predownloaded_aliscore_alicut/Aliscore.02.2.pl -O "${SCRIPT_DIR}/scripts/Aliscore.02.2.pl" && \
           wget -q https://github.com/brunoasm/my_claude_skills/tree/main/phylo_from_buscos/scripts/predownloaded_aliscore_alicut/ALICUT_V2.31.pl -O "${SCRIPT_DIR}/scripts/ALICUT_V2.31.pl" && \
	   wget -q https://github.com/brunoasm/my_claude_skills/tree/main/phylo_from_buscos/scripts/predownloaded_aliscore_alicut/Aliscore_module.pm -O "${SCRIPT_DIR}/scripts/Aliscore_module.pm"; then
	echo "Predownloaded scripts onbtained from https://github.com/brunoasm/my_claude_skills/tree/main/phylo_from_buscos/scripts/predownloaded_aliscore_alicut"
    else
        echo "ERROR: Predownloaded scripts not found at ${SKILL_BASE}"
        echo "Falling back to download option."
        SCRIPT_CHOICE="2"
    fi
fi

if [ "${SCRIPT_CHOICE}" = "2" ]; then
    echo "Downloading latest Aliscore/ALICUT scripts from GitHub..."

    # Try to download from GitHub repository
    if wget -q https://github.com/PatrickKueck/AliCUT/raw/master/Aliscore_v.2.0/Aliscore.02.2.pl -O "${SCRIPT_DIR}/scripts/Aliscore.02.2.pl" && \
       wget -q https://github.com/PatrickKueck/AliCUT/raw/master/ALICUT_V2.3.1/ALICUT_V2.31.pl -O "${SCRIPT_DIR}/scripts/ALICUT_V2.31.pl" && \
       wget -q https://github.com/PatrickKueck/AliCUT/raw/master/Aliscore_v.2.0/Aliscore_module.pm -O "${SCRIPT_DIR}/scripts/Aliscore_module.pm"; then
        chmod +x "${SCRIPT_DIR}/scripts/Aliscore.02.2.pl" "${SCRIPT_DIR}/scripts/ALICUT_V2.31.pl"
        echo "Latest scripts downloaded successfully."
    else
        echo "ERROR: Failed to download scripts from GitHub."
        echo "Please manually download from: https://github.com/PatrickKueck/AliCUT"
        exit 1
    fi
fi

# Download FASconCAT-G
echo ""
echo "Downloading FASconCAT-G for sequence concatenation..."
if wget -q https://github.com/PatrickKueck/FASconCAT-G/raw/master/FASconCAT-G_v1.05.pl -O "${SCRIPT_DIR}/scripts/FASconCAT-G.pl"; then
    chmod +x "${SCRIPT_DIR}/scripts/FASconCAT-G.pl"
    echo "FASconCAT-G downloaded successfully."
else
    echo "WARNING: Failed to download FASconCAT-G. You may need to download it manually later."
fi


echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Conda environment: ${ENV_NAME}"
echo "Perl with BioPerl: installed"
echo "Aliscore script:   ${SCRIPT_DIR}/scripts/Aliscore.02.2.pl"
echo "ALICUT script:     ${SCRIPT_DIR}/scripts/ALICUT_V2.31.pl"
echo "Aliscore module:   ${SCRIPT_DIR}/scripts/Aliscore_module.pm"
echo "FASconCAT-G:       ${SCRIPT_DIR}/scripts/FASconCAT-G.pl"
if [ -f "ASTRAL-5.7.8/Astral/astral.5.7.8.jar" ]; then
    echo "ASTRAL:            ${SCRIPT_DIR}/ASTRAL-5.7.8/Astral/astral.5.7.8.jar"
fi
echo ""
echo "To activate environment:"
echo "  conda activate ${ENV_NAME}"
echo ""
echo "Key tools installed:"
conda list | grep -E "compleasm|mafft|trimal|clipkit|bmge|iqtree|parallel|perl|ncbi-datasets-cli"
echo ""
